/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSalesRouteImport } from './routes/dashboard/sales'
import { Route as DashboardReportsRouteImport } from './routes/dashboard/reports'
import { Route as DashboardHarvestsRouteImport } from './routes/dashboard/harvests'
import { Route as DashboardFieldsRouteImport } from './routes/dashboard/fields'
import { Route as DashboardExpensesRouteImport } from './routes/dashboard/expenses'
import { Route as DashboardCropsRouteImport } from './routes/dashboard/crops'
import { Route as ApiSeedRouteImport } from './routes/api/seed'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSalesRoute = DashboardSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardHarvestsRoute = DashboardHarvestsRouteImport.update({
  id: '/harvests',
  path: '/harvests',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardFieldsRoute = DashboardFieldsRouteImport.update({
  id: '/fields',
  path: '/fields',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardExpensesRoute = DashboardExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCropsRoute = DashboardCropsRouteImport.update({
  id: '/crops',
  path: '/crops',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiSeedRoute = ApiSeedRouteImport.update({
  id: '/api/seed',
  path: '/api/seed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/api/seed': typeof ApiSeedRoute
  '/dashboard/crops': typeof DashboardCropsRoute
  '/dashboard/expenses': typeof DashboardExpensesRoute
  '/dashboard/fields': typeof DashboardFieldsRoute
  '/dashboard/harvests': typeof DashboardHarvestsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/sales': typeof DashboardSalesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/api/seed': typeof ApiSeedRoute
  '/dashboard/crops': typeof DashboardCropsRoute
  '/dashboard/expenses': typeof DashboardExpensesRoute
  '/dashboard/fields': typeof DashboardFieldsRoute
  '/dashboard/harvests': typeof DashboardHarvestsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/sales': typeof DashboardSalesRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/api/seed': typeof ApiSeedRoute
  '/dashboard/crops': typeof DashboardCropsRoute
  '/dashboard/expenses': typeof DashboardExpensesRoute
  '/dashboard/fields': typeof DashboardFieldsRoute
  '/dashboard/harvests': typeof DashboardHarvestsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/sales': typeof DashboardSalesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/api/seed'
    | '/dashboard/crops'
    | '/dashboard/expenses'
    | '/dashboard/fields'
    | '/dashboard/harvests'
    | '/dashboard/reports'
    | '/dashboard/sales'
    | '/dashboard/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/api/seed'
    | '/dashboard/crops'
    | '/dashboard/expenses'
    | '/dashboard/fields'
    | '/dashboard/harvests'
    | '/dashboard/reports'
    | '/dashboard/sales'
    | '/dashboard'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/api/seed'
    | '/dashboard/crops'
    | '/dashboard/expenses'
    | '/dashboard/fields'
    | '/dashboard/harvests'
    | '/dashboard/reports'
    | '/dashboard/sales'
    | '/dashboard/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  SignInRoute: typeof SignInRoute
  ApiSeedRoute: typeof ApiSeedRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/sales': {
      id: '/dashboard/sales'
      path: '/sales'
      fullPath: '/dashboard/sales'
      preLoaderRoute: typeof DashboardSalesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/harvests': {
      id: '/dashboard/harvests'
      path: '/harvests'
      fullPath: '/dashboard/harvests'
      preLoaderRoute: typeof DashboardHarvestsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/fields': {
      id: '/dashboard/fields'
      path: '/fields'
      fullPath: '/dashboard/fields'
      preLoaderRoute: typeof DashboardFieldsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/expenses': {
      id: '/dashboard/expenses'
      path: '/expenses'
      fullPath: '/dashboard/expenses'
      preLoaderRoute: typeof DashboardExpensesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/crops': {
      id: '/dashboard/crops'
      path: '/crops'
      fullPath: '/dashboard/crops'
      preLoaderRoute: typeof DashboardCropsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/seed': {
      id: '/api/seed'
      path: '/api/seed'
      fullPath: '/api/seed'
      preLoaderRoute: typeof ApiSeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardCropsRoute: typeof DashboardCropsRoute
  DashboardExpensesRoute: typeof DashboardExpensesRoute
  DashboardFieldsRoute: typeof DashboardFieldsRoute
  DashboardHarvestsRoute: typeof DashboardHarvestsRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardSalesRoute: typeof DashboardSalesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardCropsRoute: DashboardCropsRoute,
  DashboardExpensesRoute: DashboardExpensesRoute,
  DashboardFieldsRoute: DashboardFieldsRoute,
  DashboardHarvestsRoute: DashboardHarvestsRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardSalesRoute: DashboardSalesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  SignInRoute: SignInRoute,
  ApiSeedRoute: ApiSeedRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
